services:
  - docker:dind

stages:
  - test
  - deploy

run-test:
  image: openjdk:11.0.12
  stage: test
  script: ./gradlew allTests
  only:
    - trunk
    - external_pull_requests

deploy-container:
  image: docker:stable
  stage: deploy
  variables:
    TAGGED_IMAGE: "$IMAGE_TAG:$CI_COMMIT_SHORT_SHA"
    LATEST_IMAGE: "$IMAGE_TAG:latest"
  script:
    - docker login -u $GITLAB_USER_LOGIN -p $GITLAB_API_KEY registry.gitlab.com
    - docker build -t $TAGGED_IMAGE .
    - docker tag $TAGGED_IMAGE $LATEST_IMAGE
    - docker push $IMAGE_TAG
  only:
    - trunk